### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by aliciapaz**
## Friendship update
This pull request seeks to improve the creation and updating of friendships in the app.

Mutual friendship was already implemented in the last milestone through:
- `:check_uniqueness` validation: allows to create a friendship between two users only if no other friendship already exists for these users, no matter who the requester and the requestee are.  
- `#bidirectional_friendship(user1, user2)`: finds a friendship between two users, no matter who the requester/requestee is. This allows filtering the users for whom the 'invite to friendship' option is displayed.
- `#unidirectional_friendship(user2, user2)`: finds a friendship between two users, looking for only one direction.  This allows filtering the users for whom the 'accept' and 'reject' options are displayed, by looking for friendships in which the `current_user` is the requestee.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @aliciapaz and @george-shammar   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] One of your Rspec tests is failing. Please fix it.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by george-shammar** [comment]
Hello, @Temmarie All the Rspec tests are passing here. I've just tested it again. Could you please be specific as to which of the tests is failing?

Thanks.

**Comment by Temmarie** [comment]
Hi @george-shammar , here is the failing test:
18 examples, 1 failure

```
Failed examples:

rspec ./spec/helpers/application_helper_spec.rb:5 # ApplicationHelper index page shows like_or_dislike_btn

```

**Comment by george-shammar** [comment]
test
All Rspec tests are passing.

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @aliciapaz and @george-shammar ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:
 
#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
